Fixed a regression where type change in :func:`ExceptionInfo.errisinstance` caused `mypy` to fail.
