Fixed a regression where type change in `ExceptionInfo.errisinstance` caused `mypy` to fail.
